### ISSUE TITLE
Step 6: No need to `sudo chown $(whoami) /dev/kvm`

### ISSUE THREAD

**Issue by etam** [MarijnStevens/yagna-binaries#10]
After adding the user to `kvm` group, it's enough to re-login.

**Comment by MarijnStevens** [comment]
hmmm.. Can you do it with su also ?

**Comment by etam** [comment]
I don't understand.

What I'm saying is that by default `/dev/kvm` has permissions
```shell
$ ls -la /dev/kvm
crw-rw----+ 1 root kvm 10, 232 kwi 22 02:15 /dev/kvm
```
This means that any user in `kvm` group can access it.

The command `sudo adduser $(whoami) kvm` from the instruction adds the current user to the `kvm` group, but to make it apply, it's required to log out and in again.

**Comment by MarijnStevens** [comment]
Alright, I've made the changes in a reworked repo over at https://github.com/MarijnStevens/yagna-aarch64/ 

> https://github.com/MarijnStevens/yagna-aarch64/blob/master/yagna-binaries/install.sh

It was hidden but has yagna, ya-runtime-vm, ya-runtime-wasi as submodules, preparing for an CI build, so we can keep up to date with upstream.

**Comment by MarijnStevens** [comment]
Update install instructions eae4c6b7991c49f22e6e3ae1568e3758c6f69116
