### ISSUE TITLE
Q: Why is libpixman-1-dev required?

### ISSUE THREAD

**Issue by etam** [MarijnStevens/yagna-binaries#11]
Isn't `libpixman-1-0` enough?

**Comment by MarijnStevens** [comment]
Have you tried that ? I build the first qemu on the pi itself, so I believe that's why I had that dependency in the first place. Static compiling the qemu binary is a little difficult for various reasons.  (You seem to be right on first glance)

**Comment by etam** [comment]
A `-dev` (which contains header files and other config files used by build system) package is needed for building qemu, but for running only the shared library (provided by `libpixman-1-0`) is needed.

**Comment by MarijnStevens** [comment]
Fixed the instructions. 👍
